version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gym_partner_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
  gym-partner-api:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: gym_partner_db
      DB_USER: user
      DB_PASSWORD: userpassword
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app